name: Terraform IaC Deployment to AWS

on:
  push:
    branches:
      - '**'
    paths:
      - 'aws/**'
      - '.github/workflows/infra-aws.yml'
  workflow_dispatch:

# Need ID token write permission to use OIDC
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  terraform:
    name: 'Terraform AWS Deployment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          role-session-name: GitHubActions-Deploy

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Run Lambda Package Script
        working-directory: aws/view_counter
        run: |
          chmod +x ./package_code.sh
          ./package_code.sh
          # Move the generated zip files to the terraform directory
          mv lambda_package.zip ../terraform/
          mv dependencies.zip ../terraform/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Terraform Init
        working-directory: aws/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: aws/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: aws/terraform
        run: terraform apply -auto-approve
